### ISSUE TITLE
Document coefficients, used in the score formulas

### ISSUE THREAD

**Issue by poruchikrj** [Cyb3r-Monk/RITA-J#1]
Would it be possible to either document or comment out all coefficients, used in the last part of the score calculation?
For instance:
http_df['dsMadmScore'] = 1.0 - (http_df['dsMadm'] / **_128.0_**) or 
http_df['Score'] = (http_df['dsScore'] + http_df['tsScore']) / **_2_**

Why did you use specifically those values? 

I checked the same calculations in the original RITA analyzed source code and almost all coefficients are different. And they are not described too:)

You did an awesome work here but it would great to understand your decisions. Thus, we can adapt your source code to other log sources, use cases etc.

**Comment by Cyb3r-Monk** [comment]
Thanks for the feedback! I'll add details about calculations soon!

**Comment by Cyb3r-Monk** [comment]
I've added some explanations.
